/*
Q.44 Pentagon Numbers
"Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?"
 */

package Day10;

import java.util.ArrayList;

public class Pentagon_Numbers {

    public static ArrayList <Integer> generatePentagonal(int limit){

        ArrayList<Integer> pentagon = new ArrayList<Integer>();

        int result = 0;

        for (int i=1;i<=limit;i++)
        {
            result = (3*i*i - i)/2;
            pentagon.add(result);
        }

        //System.out.println(pentagon.size());

        return pentagon;
    }

    public static boolean isPentagonal(int num)
    {
        int temp = 0,i=1;

        do {
            temp = (3*i*i - i)/2;
            i+=1;
        }while (temp<num);

        return (temp == num);
    }

    public static long minimisedPentagonal()
    {
        var arr = generatePentagonal(3000);
        var res = 0;

        for (int i = 0;i<arr.size();i++)
        {
            for (int j=i+1;j<arr.size();j++)
            {
                if (isPentagonal(arr.get(j) - arr.get(i)) && isPentagonal(arr.get(i) + arr.get(j))){
                    res = Math.abs(arr.get(i)-arr.get(j));
                    break;
                }
            }
        }
        return res;
    }

    public static void main(String[] args) {
        long start = System.currentTimeMillis();
        System.out.println(minimisedPentagonal());
        long end = System.currentTimeMillis();
        System.out.println("Execution Time: "+(end-start)/1000F+" seconds");
    }
}
